from enum import Flag, auto
from pathlib import Path
from .user_input import KeyboardKey as key
#from .objects import SprayPowerUp

SPACESHIP_WIDTH = 20
SPACESHIP_HEIGHT = 20
SPACESHIP_HITBOX_WIDTH = SPACESHIP_WIDTH
SPACESHIP_HITBOX_HEIGHT = SPACESHIP_HEIGHT
SPACESHIP_INERTIA_FACTOR = 0.9
SPACESHIP_ACCELERATION = 1.2
SPACESHIP_SHOT_COOLDOWN = 6

STONE_SIZES = [2, 3, 4]
STONE_BASE_RADIUS = 12
STONE_BASE_HITBOX_RADIUS = STONE_BASE_RADIUS
STONE_STANDARD_MIN_Y_VEL = 0.2
STONE_STANDARD_MAX_VEL = 0.4
STONE_COLOR = (0, 255, 0)

ENEMY_WIDTH = 15
ENEMY_HEIGHT = 15
ENEMY_HITBOX_WIDTH = ENEMY_WIDTH
ENEMY_HITBOX_HEIGHT = ENEMY_HEIGHT
ENEMY_STANDARD_MIN_Y_VEL = 0.5
ENEMY_STANDARD_MAX_VEL = 1
ENEMY_TYPES = [0,1,2,3]
ENEMY_COLOR = (200, 255, 0)
ENEMY_SHOT_COOLDOWN = 32

PROJECTILE_WIDTH = 4
PROJECTILE_HEIGHT = 12
PROJECTILE_HITBOX_WIDTH = PROJECTILE_WIDTH
PROJECTILE_HITBOX_HEIGHT = PROJECTILE_HEIGHT
PROJECTILE_SPEED = 8

POWERUP_HITBOX_RADIUS = 12
POWERUP_SPEED = 2
POWERUP_TYPES = []#[SprayPowerUp, InvincibilityPowerUp, DoublePointsPowerUp]#, SlowDownPowerUp, MultiShotPowerUp, PiercingPowerUp] # Jedes PowerUp wird hier festgelegt. Die Liste kann beliebig erweitewrt werden.
POWERUP_COLORS = [(100, 100, 100), (2, 2, 2), (3, 3, 3), (4, 4, 4), (4, 4, 4), (4, 4, 4)]


SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400

POS_SCORE = (SCREEN_WIDTH / 2, 12)
TEXT_SIZE_SCORE = 32
TEXT_COLOR_SCORE = (200, 200, 200)

START_STONE_SPAWNING_PROBABILITY = 0.01
STONE_SPAWNING_PROPABILITY_INCREASE = 0.000005
STONE_SPAWNING_PROPABILITY_INCREASE_DECREASE = 5

START_POWERUP_SPAWNING_PROBABILITY = 0.001
POWERUP_SPAWNING_PROPABILITY_INCREASE = 0.0000005
POWERUP_SPAWNING_PROPABILITY_INCREASE_DECREASE = 0.5

START_ENEMY_SPAWNING_PROBABILITY = 0.002
ENEMY_SPAWNING_PROPABILITY_INCREASE = 0.000001
ENEMY_SPAWNING_PROPABILITY_INCREASE_DECREASE = 1

SIZE_LIVES = (32, 32)
D_POS_LIVES = (8, 8)
POS_LIVES = (D_POS_LIVES[0], SCREEN_HEIGHT - SIZE_LIVES[1] - D_POS_LIVES[1])
LIFE_ICON_DISTANCE = 8

GAME_OVER_LINE_HEIGHT = 24

# Paths

GAME_PATH = Path(__file__).parent
IMAGES_PATH = GAME_PATH / "images"
SOUNDS_PATH = GAME_PATH / "sounds"
FONTS_PATH = GAME_PATH / "fonts"

HEART_IMAGE_PATH = IMAGES_PATH / "heart.png"
BACKGROUNG_IMAGE_PATH = IMAGES_PATH / "background.jpg"

SHOOT_SOUND_PATH = SOUNDS_PATH / "shoot.wav"
HIT_SOUND_PATH = SOUNDS_PATH / "hit.wav"
EXPLOSION_SOUND_PATH = SOUNDS_PATH / "explosion.wav"

FONT_NAME = FONTS_PATH / "8bitoperator_jve.ttf"

# Unique message values

class DrawDetails(Flag):
    NONE = 0
    TOP_LAYER = auto()
