from enum import Flag, auto
from pathlib import Path
import pygame
from .user_input import KeyboardKey as key
import math

FRAME = 1
SECOND = 60
degrees_to_radians = math.radians

LEADERBOARD_MAX_ENTRIES = 10

SPACESHIP_WIDTH = 32
SPACESHIP_HEIGHT = 32
SPACESHIP_HITBOX_WIDTH = SPACESHIP_WIDTH
SPACESHIP_HITBOX_HEIGHT = SPACESHIP_HEIGHT
SPACESHIP_INERTIA_FACTOR = 0.9
SPACESHIP_ACCELERATION = 0.8
SPACESHIP_SHOT_COOLDOWN = 12
SPACESHIP_DAMAGE = 50
SPACESHIP_SHIELD_COLOR = pygame.Color(100, 100, 255, 100)

STONE_SIZES = [2, 3, 4]
STONE_BASE_RADIUS = 12
STONE_BASE_HITBOX_RADIUS = STONE_BASE_RADIUS
STONE_STANDARD_MIN_Y_VEL = 0.1
STONE_STANDARD_MAX_VEL = 0.2
STONE_LIVES = 100
STONE_COLOR = (200, 255, 0)

ENEMY_WIDTH = 32
ENEMY_HEIGHT = 32
ENEMY_HITBOX_WIDTH = ENEMY_WIDTH
ENEMY_HITBOX_HEIGHT = ENEMY_HEIGHT
ENEMY_STANDARD_MIN_Y_VEL = 0.5
ENEMY_STANDARD_MAX_VEL = 1
ENEMY_COLOR = (200, 255, 0)
ENEMY_LIVES = 200
ENEMY_SHOT_COOLDOWN = 150

PROJECTILE_WIDTH = 4
PROJECTILE_HEIGHT = 12
PROJECTILE_HITBOX_WIDTH = PROJECTILE_WIDTH
PROJECTILE_HITBOX_HEIGHT = PROJECTILE_HEIGHT
PROJECTILE_SPEED = 240 / SECOND
PROJECILE_MULTISHOT_ANGLE = degrees_to_radians(15)

FIRE_PROJECTILE_WIDTH = 24
FIRE_PROJECTILE_HEIGHT = 36
FIRE_PROJECTILE_HITBOX_WIDTH = FIRE_PROJECTILE_WIDTH
FIRE_PROJECTILE_HITBOX_HEIGHT = FIRE_PROJECTILE_HEIGHT
FIRE_PROJECTILE_SPEED = 120 / SECOND

WAVE_PROJECTILE_WIDTH = 4
WAVE_PROJECTILE_HEIGHT = 2
WAVE_PROJECTILE_HITBOX_WIDTH = WAVE_PROJECTILE_WIDTH
WAVE_PROJECTILE_HITBOX_HEIGHT = WAVE_PROJECTILE_HEIGHT
WAVE_GROW_RATE = 60 / SECOND
WAVE_PROJECTILE_SPEED = 160 / SECOND

FIRE_ENEMY_SHOT_COOLDOWN = 150

BOSS_ENEMY_LIVES = 3000
BOSS_ENEMY_SHOT_COOLDOWN = 100
BOSS_ENEMY_WIDTH = 64
BOSS_ENEMY_HEIGHT = 64
BOSS_ENEMY_HITBOX_WIDTH = BOSS_ENEMY_WIDTH
BOSS_ENEMY_HITBOX_HEIGHT = BOSS_ENEMY_HEIGHT
BOSS_ENEMY_MOVEMENT_FREQUENCY = degrees_to_radians(9 / SECOND)
BOSS_ENEMY_MAX_SPEED = 90 / SECOND
BOSS_ENEMY_SCORE = 3200
BOSS_BAR_WIDTH = 100
BOSS_BAR_COLOR = (255, 0, 0)

SCORE_ENEMY = 200
SCORE_STONE = 100

PIERCING_PROJECTILE_ENEMY_COOLDOWN = 15

POWERUP_HITBOX_RADIUS = 12
POWERUP_SPEED = 90 / SECOND
POWERUP_COLORS = [(100, 100, 100), (2, 2, 2), (3, 3, 3), (4, 4, 4), (4, 4, 4), (4, 4, 4)]
POWERUP_HEIGHT = 32
POWERUP_WIDTH = 32

HEALTH_BAR_BACKGROUND_COLOR = (100, 100, 100)
HEALTH_BAR_COLOR = (0, 255, 0)
HEALTH_BAR_SLICE_COLOR = (50, 50, 50)
HEALTH_BAR_WIDTH = 50
HEALTH_BAR_HEIGHT = 10
HEALTH_BAR_SLICE_WIDTH = 2

ARC_COOLDOWN_RADIUS = 16
ARC_COOLDOWN_COLOR = (200, 200, 200)

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400

POS_SCORE = (SCREEN_WIDTH / 2, 12)
TEXT_SIZE_SCORE = 32
TEXT_COLOR_SCORE = (200, 200, 200)

POS_CREDITS = (SCREEN_WIDTH / 2, 36)
TEXT_SIZE_CREDITS = 24
TEXT_COLOR_CREDITS = (255, 255, 0)

START_STONE_SPAWNING_PROBABILITY = 0.002 / FRAME
STONE_SPAWNING_PROPABILITY_INCREASE = 0.000001
STONE_SPAWNING_PROPABILITY_INCREASE_DECREASE = 5
STONE_TURNING_SPEED_MIN = -6 / SECOND # Degrees
STONE_TURNING_SPEED_MAX = 6 / SECOND

START_POWERUP_SPAWNING_PROBABILITY = 0.001 / FRAME
POWERUP_SPAWNING_PROPABILITY_INCREASE = 0.0000000
POWERUP_SPAWNING_PROPABILITY_INCREASE_DECREASE = 0.5

ENEMY_TARGET_HEIGHT_RANGE = range(ENEMY_HEIGHT // 2 + 16, ENEMY_HEIGHT // 2 + 48)
ENEMY_SPAWN_COOLDOWN = 157

SIZE_LIVES = (32, 32)
D_POS_LIVES = (8, 8)
POS_LIVES = (D_POS_LIVES[0], SCREEN_HEIGHT - SIZE_LIVES[1] - D_POS_LIVES[1])
LIFE_ICON_DISTANCE = 8

GAME_OVER_LINE_HEIGHT = 24

# Paths

GAME_PATH = Path(__file__).parent
IMAGES_PATH = GAME_PATH / "images"
SOUNDS_PATH = GAME_PATH / "sounds"
FONTS_PATH = GAME_PATH / "fonts"

HEART_IMAGE_PATH = IMAGES_PATH / "heart.png"
BACKGROUND_IMAGE_PATH = IMAGES_PATH / "pixel_background_1.jpeg"
SPACESHIP_IMAGE_PATH = IMAGES_PATH / "ship_2.png"
ENEMY_IMAGE_PATH = IMAGES_PATH / "ship_3.png"
PIERCING_ENEMY_IMAGE_PATH = IMAGES_PATH / "ship_1.png"
FIRE_ENEMY_IMAGE_PATH = IMAGES_PATH / "ship_4.png"
BOSS_ENEMY_IMAGE_PATH = IMAGES_PATH / "boss_ship.png"
POWERUP_DOUBLEPOINTS_IMAGE_PATH = IMAGES_PATH / "points_star.png"
POWERUP_DOUBLEDAMAGE_IMAGE_PATH = IMAGES_PATH / "damage_star.png"
POWERUP_DOUBLESPEED_IMAGE_PATH = IMAGES_PATH / "speed_star.png"
POWERUP_MULTISHOT_IMAGE_PATH = IMAGES_PATH / "multi_star.png"
POWERUP_INVINCIBILITY_IMAGE_PATH = IMAGES_PATH / "invincibility_star.png"
POWERUP_STRIKE_IMAGE_PATH = IMAGES_PATH / "penetration_star.png"
STONE_IMAGE_PATH = IMAGES_PATH / "stone.png"

SHOOT_SOUND_PATH = SOUNDS_PATH / "shoot.ogg"
HIT_SOUND_PATH = SOUNDS_PATH / "hit.ogg"
EXPLOSION_SOUND_PATH = SOUNDS_PATH / "explosion.ogg"
POWERUP_SOUND_PATH = SOUNDS_PATH / "powerup.ogg"

FONT_NAME = FONTS_PATH / "8bitoperator_jve.ttf"

# Unique message values

class DrawDetails(Flag):
    NONE = 0
    TOP_LAYER = auto()
