from .user_input import KeyboardKey as key

SPACESHIP_WIDTH = 20
SPACESHIP_HEIGHT = 20
SPACESHIP_HITBOX_WIDTH = SPACESHIP_WIDTH
SPACESHIP_HITBOX_HEIGHT = SPACESHIP_HEIGHT
SPACESHIP_INERTIA_FACTOR = 0.9
SPACESHIP_ACCELERATION = 1.2

STONE_SIZES = [2, 3, 4]
STONE_BASE_RADIUS = 12
STONE_BASE_HITBOX_RADIUS = STONE_BASE_RADIUS

PROJECTILE_WIDTH = 4
PROJECTILE_HEIGHT = 12
PROJECTILE_HITBOX_WIDTH = PROJECTILE_WIDTH
PROJECTILE_HITBOX_HEIGHT = PROJECTILE_HEIGHT
PROJECTILE_SPEED = 8

SCREEN_WIDTH = 400
SCREEN_HEIGHT = 400

POS_SCORE = (12, 12)
TEXT_SIZE_SCORE = 12 
TEXT_COLOR_SCORE = (100, 100, 100)

START_STONE_SPAWNING_PROBABILITY = 0.01
STONE_SPAWNING_PROPABILITY_INCREASE = 0.000005
STONE_SPAWNING_PROPABILITY_INCREASE_DECREASE = 5